- src: git+https://github.com/dometto/ansible-galaxy.git,prebuilt_client
  name: galaxyproject.galaxy 
  version: 0.10.14
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
