---
roles:
  - src: https://github.com/galaxyproject/ansible-galaxy.git
    name: galaxyproject.galaxy
    version: 08974b18e2aad1e5569854e5d6c8b5c966bf55e4
  - src: https://github.com/utrechtuniversity/ansible-galaxy-tools.git
    name: galaxyproject.galaxy-tools
  - src: galaxyproject.postgresql
    version: 1.1.8
  - src: galaxyproject.postgresql_objects
    version: 1.2.1
  - src: geerlingguy.docker
    version: 6.1.0
  - name: galaxyproject.tusd
    src: https://github.com/galaxyproject/ansible-role-tusd.git
    version: e009b498a7989d8002c6a5d104176295d63e9fae
  - src: galaxyproject.cvmfs
    version: 0.2.21
collections:
  - name: community.general
  - name: community.postgresql
  - name: https://github.com/UtrechtUniversity/researchcloud-items.git # uusrc.general
    type: git
    version: 5cf6f0141f09a0f4853cacd3abb3604f43153cb4
